In [3]:
import numpy as np
import pandas as pd

In [4]:
import tensorflow as ts
import keras as keras 

Using TensorFlow backend.


In [5]:
dataset = pd.read_csv(r'C:\Users\bhavani\Downloads\Admission_Predict_Ver1.1.csv')

In [6]:
dataset

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
5             6        330          115                  5  4.5   3.0  9.34   
6             7        321          109                  3  3.0   4.0  8.20   
7             8        308          101                  2  3.0   4.0  7.90   
8             9        302          102                  1  2.0   1.5  8.00   
9            10        323          108                  3  3.5   3.0  8.60   
10           11        325          106                  3  3.5   4.0  8.40   
11           12        327          111                  4  4.0   4.5  9.00   
12           13        328          112                  4  4.0   4.5  9.10   
13           14        307          109                  3  4.0   3.0  8.00   
14           15        311          104                  3  3.5   2.0  8.20   
15           16        314          105                  3  3.5   2.5  8.30   
16           17        317          107                  3  4.0   3.0  8.70   
17           18        319          106                  3  4.0   3.0  8.00   
18           19        318          110                  3  4.0   3.0  8.80   
19           20        303          102                  3  3.5   3.0  8.50   
20           21        312          107                  3  3.0   2.0  7.90   
21           22        325          114                  4  3.0   2.0  8.40   
22           23        328          116                  5  5.0   5.0  9.50   
23           24        334          119                  5  5.0   4.5  9.70   
24           25        336          119                  5  4.0   3.5  9.80   
25           26        340          120                  5  4.5   4.5  9.60   
26           27        322          109                  5  4.5   3.5  8.80   
27           28        298           98                  2  1.5   2.5  7.50   
28           29        295           93                  1  2.0   2.0  7.20   
29           30        310           99                  2  1.5   2.0  7.30   
..          ...        ...          ...                ...  ...   ...   ...   
470         471        320          110                  5  4.0   4.0  9.27   
471         472        311          103                  3  2.0   4.0  8.09   
472         473        327          116                  4  4.0   4.5  9.48   
473         474        316          102                  2  4.0   3.5  8.15   
474         475        308          105                  4  3.0   2.5  7.95   
475         476        300          101                  3  3.5   2.5  7.88   
476         477        304          104                  3  2.5   2.0  8.12   
477         478        309          105                  4  3.5   2.0  8.18   
478         479        318          103                  3  4.0   4.5  8.49   
479         480        325          110                  4  4.5   4.0  8.96   
480         481        321          102                  3  3.5   4.0  9.01   
481         482        323          107                  4  3.0   2.5  8.48   
482         483        328          113                  4  4.0   2.5  8.77   
483         484        304          103                  5  5.0   3.0  7.92   
484         485        317          106                  3  3.5   3.0  7.89   
485         486        311          101                  2  2.5   3.5  8.34   
486         487        319          102                  3  2.5   2.5  8.37   
487         488        327          115                  4  3.5   4.0  9.14   
488         489        322          112                

In [7]:
dataset.isnull().any()

Serial No.           False
GRE Score            False
TOEFL Score          False
University Rating    False
SOP                  False
LOR                  False
CGPA                 False
Research             False
Chance of Admit      False
dtype: bool

In [11]:
x=dataset.iloc[:,:8].values

In [12]:
x

array([[  1.  , 337.  , 118.  , ...,   4.5 ,   9.65,   1.  ],
       [  2.  , 324.  , 107.  , ...,   4.5 ,   8.87,   1.  ],
       [  3.  , 316.  , 104.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [498.  , 330.  , 120.  , ...,   5.  ,   9.56,   1.  ],
       [499.  , 312.  , 103.  , ...,   5.  ,   8.43,   0.  ],
       [500.  , 327.  , 113.  , ...,   4.5 ,   9.04,   0.  ]])

In [13]:
x.shape

(500, 8)

In [25]:
y = dataset.iloc[:,8:].values

In [28]:
y

array([[0.92],
       [0.76],
       [0.72],
       [0.8 ],
       [0.65],
       [0.9 ],
       [0.75],
       [0.68],
       [0.5 ],
       [0.45],
       [0.52],
       [0.84],
       [0.78],
       [0.62],
       [0.61],
       [0.54],
       [0.66],
       [0.65],
       [0.63],
       [0.62],
       [0.64],
       [0.7 ],
       [0.94],
       [0.95],
       [0.97],
       [0.94],
       [0.76],
       [0.44],
       [0.46],
       [0.54],
       [0.65],
       [0.74],
       [0.91],
       [0.9 ],
       [0.94],
       [0.88],
       [0.64],
       [0.58],
       [0.52],
       [0.48],
       [0.46],
       [0.49],
       [0.53],
       [0.87],
       [0.91],
       [0.88],
       [0.86],
       [0.89],
       [0.82],
       [0.78],
       [0.76],
       [0.56],
       [0.78],
       [0.72],
       [0.7 ],
       [0.64],
       [0.64],
       [0.46],
       [0.36],
       [0.42],
       [0.48],
       [0.47],
       [0.54],
       [0.56],
       [0.52],
       [0.55],
       [0.

In [29]:
y.shape

(500, 1)

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [31]:
x_test

array([[ 91.  , 318.  , 106.  ,   2.  ,   4.  ,   4.  ,   7.92,   1.  ],
       [255.  , 321.  , 114.  ,   4.  ,   4.  ,   5.  ,   9.12,   0.  ],
       [284.  , 321.  , 111.  ,   3.  ,   2.5 ,   3.  ,   8.9 ,   1.  ],
       [446.  , 328.  , 116.  ,   5.  ,   4.5 ,   5.  ,   9.08,   1.  ],
       [462.  , 301.  , 102.  ,   3.  ,   2.5 ,   2.  ,   8.13,   1.  ],
       [ 16.  , 314.  , 105.  ,   3.  ,   3.5 ,   2.5 ,   8.3 ,   0.  ],
       [317.  , 298.  , 101.  ,   2.  ,   1.5 ,   2.  ,   7.86,   0.  ],
       [490.  , 302.  , 110.  ,   3.  ,   4.  ,   4.5 ,   8.5 ,   0.  ],
       [160.  , 297.  , 100.  ,   1.  ,   1.5 ,   2.  ,   7.9 ,   0.  ],
       [154.  , 324.  , 105.  ,   3.  ,   3.  ,   4.  ,   8.75,   0.  ],
       [242.  , 317.  , 103.  ,   2.  ,   2.5 ,   2.  ,   8.15,   0.  ],
       [251.  , 320.  , 104.  ,   3.  ,   3.  ,   2.5 ,   8.57,   1.  ],
       [391.  , 314.  , 102.  ,   2.  ,   2.  ,   2.5 ,   8.24,   0.  ],
       [290.  , 313.  , 109.  ,   3.  ,   4.  ,   3

In [32]:
import keras
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(input_dim=8,init="random_uniform",output_dim=30))
model.add(Dense(init="random_uniform",output_dim=30))
model.add(Dense(init="random_uniform",output_dim=1))
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['mse'])
model.fit(x_train,y_train,epochs=100,batch_size=32)

C:\Users\bhavani\Anaconda3\New folder\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=8, units=30, kernel_initializer="random_uniform")`
  """
C:\Users\bhavani\Anaconda3\New folder\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=30, kernel_initializer="random_uniform")`
  
C:\Users\bhavani\Anaconda3\New folder\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="random_uniform")`
  import sys


Epoch 1/100
400/400 [==============================] - 3s 7ms/step - loss: 0.2461 - mean_squared_error: 0.2461
Epoch 2/100
400/400 [==============================] - 0s 703us/step - loss: 0.0406 - mean_squared_error: 0.0406
Epoch 3/100
400/400 [==============================] - 0s 469us/step - loss: 0.0220 - mean_squared_error: 0.0220
Epoch 4/100
400/400 [==============================] - 0s 781us/step - loss: 0.0172 - mean_squared_error: 0.0172
Epoch 5/100
400/400 [==============================] - 0s 977us/step - loss: 0.0150 - mean_squared_error: 0.0150
Epoch 6/100
400/400 [==============================] - 0s 1ms/step - loss: 0.0144 - mean_squared_error: 0.0144
Epoch 7/100
400/400 [==============================] - 0s 664us/step - loss: 0.0145 - mean_squared_error: 0.0145
Epoch 8/100
400/400 [==============================] - 0s 625us/step - loss: 0.0145 - mean_squared_error: 0.0145
Epoch 9/100
400/400 [==============================] - 0s 859us/step - loss: 0.0143 - mean_squared_e

Epoch 71/100
400/400 [==============================] - 0s 352us/step - loss: 0.0061 - mean_squared_error: 0.0061
Epoch 72/100
400/400 [==============================] - 0s 781us/step - loss: 0.0063 - mean_squared_error: 0.0063
Epoch 73/100
400/400 [==============================] - 0s 625us/step - loss: 0.0070 - mean_squared_error: 0.0070
Epoch 74/100
400/400 [==============================] - 0s 820us/step - loss: 0.0065 - mean_squared_error: 0.0065
Epoch 75/100
400/400 [==============================] - 0s 430us/step - loss: 0.0063 - mean_squared_error: 0.0063
Epoch 76/100
400/400 [==============================] - 0s 820us/step - loss: 0.0067 - mean_squared_error: 0.00670s - loss: 0.0071 - mean_squared_error: 
Epoch 77/100
400/400 [==============================] - 0s 234us/step - loss: 0.0064 - mean_squared_error: 0.0064
Epoch 78/100
400/400 [==============================] - 0s 586us/step - loss: 0.0070 - mean_squared_error: 0.0070
Epoch 79/100
400/400 [==========================

In [33]:
y_pred=model.predict(x_test)

In [34]:
y_pred

array([[0.7255151 ],
       [0.8204742 ],
       [0.7480123 ],
       [0.94497585],
       [0.69940984],
       [0.6404088 ],
       [0.56805825],
       [0.78885686],
       [0.51786447],
       [0.680123  ],
       [0.58702624],
       [0.70515084],
       [0.60121703],
       [0.73564416],
       [0.89202565],
       [0.556127  ],
       [0.8766483 ],
       [0.6402012 ],
       [0.6835636 ],
       [0.51558805],
       [0.59400606],
       [0.7777004 ],
       [0.57944703],
       [0.92098117],
       [0.8601074 ],
       [0.7135407 ],
       [0.6867864 ],
       [0.5194647 ],
       [0.59674567],
       [0.6140569 ],
       [0.66418546],
       [0.60480666],
       [0.6829708 ],
       [0.8754368 ],
       [0.6087606 ],
       [0.78587115],
       [0.8363076 ],
       [0.89287233],
       [0.6684501 ],
       [0.65149105],
       [0.6692267 ],
       [0.879955  ],
       [0.8627447 ],
       [0.7278964 ],
       [0.73742324],
       [0.7963114 ],
       [0.9384413 ],
       [0.827

In [35]:
y_test

array([[0.64],
       [0.85],
       [0.8 ],
       [0.91],
       [0.68],
       [0.54],
       [0.54],
       [0.65],
       [0.52],
       [0.79],
       [0.65],
       [0.74],
       [0.64],
       [0.79],
       [0.89],
       [0.43],
       [0.81],
       [0.73],
       [0.8 ],
       [0.58],
       [0.57],
       [0.74],
       [0.6 ],
       [0.93],
       [0.88],
       [0.67],
       [0.7 ],
       [0.57],
       [0.48],
       [0.64],
       [0.69],
       [0.47],
       [0.57],
       [0.87],
       [0.39],
       [0.53],
       [0.84],
       [0.89],
       [0.63],
       [0.7 ],
       [0.72],
       [0.86],
       [0.91],
       [0.75],
       [0.74],
       [0.76],
       [0.96],
       [0.81],
       [0.6 ],
       [0.62],
       [0.69],
       [0.68],
       [0.59],
       [0.8 ],
       [0.71],
       [0.78],
       [0.69],
       [0.89],
       [0.67],
       [0.58],
       [0.44],
       [0.89],
       [0.53],
       [0.92],
       [0.66],
       [0.73],
       [0.

In [36]:
y_pred[25]

array([0.7135407], dtype=float32)

In [37]:
y_test[25]

array([0.67])

In [41]:
y_pred_single=model.predict(np.array([[2,324,107,4,4.0,4.5,8.87,1]]))
y_pred_single

array([[0.7963114]], dtype=float32)

In [42]:
y_test_single=model.predict(np.array([[2,324,107,4,4.0,4.5,8.87,1]]))
y_test_single

array([[0.7963114]], dtype=float32)

In [43]:
y_pred_single=model.predict(np.array([[25,336,119,5,4.0,3.5,9.8,1]]))
y_pred_single

array([[0.8670904]], dtype=float32)

In [44]:
y_test_single=model.predict(np.array([[25,336,119,5,4.0,3.5,9.8,1]]))
y_test_single

array([[0.8670904]], dtype=float32)